trailingComma: "es5"
tabWidth: 2
semi: true
printWidth: 120
useTabs: false
singleQuote: false
jsxSingleQuote: false
quoteProps: "as-needed"
bracketSpacing: true
bracketSameLine: false
arrowParens: "always"
endOfLine: "lf"
singleAttributePerLine: false
